query getAllMachinesDropdown{
    machines {
        value:id
        label
    }
}


query Machines($limit: Int, $orderBy: MachinesOrderByWithRelationInput, $offset: Int, $where: MachinesWhereInput) {
    machines(limit: $limit,orderBy: $orderBy,offset: $offset,where: $where) {
        id
        label
        name
        priority
        profile
        section {
            id
            name
        }
        machine_catagory {
        name 
        }
        block {
            id
            name
        }
        priority
    }
}



query MachinesCount($limit: Int, $orderBy: MachinesOrderByWithRelationInput, $offset: Int, $where: MachinesWhereInput) {
    machinesCount(limit: $limit,orderBy: $orderBy,offset: $offset,where: $where)
}

mutation removeMachine($removeMachineId: Int!) {
  removeMachine(id: $removeMachineId) {
    id
  }
}

mutation createMachine($createMachineInput: MachinesCreateInput!) {
  createMachine(createMachineInput: $createMachineInput) {
    id
  }
}

mutation updateMachine($updateMachineId: Int!, $updateMachineInput: MachinesUpdateInput!) {
  updateMachine(id: $updateMachineId, updateMachineInput: $updateMachineInput) {
     id
  }
}