name: Build and Deploy React App to CloudFront

"on":
  push:
    branches:
      - production
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      VITE_ENDPOINT: https://server.easycmms.infraweigh.co
      VITE_APP_NAME: easy cmms
      VITE_BASE_URL: https://app.easycmms.infraweigh.co
      VITE_ENV: production
      BUCKET: app.easycmms.infraweigh.co
      DIST: dist
      REGION: us-east-1
      DIST_ID: E1SD90E24VNFIL
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn install

      - name: Build Static Website
        run: yarn build

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
